name: 🐞 Bug Report
description: Report a reproducible issue or unexpected behavior in Charm
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Short Summary
      placeholder: "Briefly describe the problem"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Description
      description: "What happened? Steps to reproduce or any relevant info."
      placeholder: |
        1. Run `charm ...`
        2. See error message ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Charm Version
      placeholder: "e.g. v0.1.2"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues.
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md).
          required: true
