name: 💡 Feature Request
description: Suggest a new idea or improvement for Charm
title: "[Feature]: "
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: "Briefly describe your idea"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Description
      description: "What problem does this feature solve or what value would it add?"
      placeholder: "It would be great if Charm could..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked for similar feature requests.
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md).
          required: true
