name: 💡 Feature Request
description: Suggest a new idea, enhancement, or integration for Charm
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        We're excited to hear your ideas!  
        Please describe what you’d like to see added or improved.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: "Briefly summarize your idea."
      placeholder: "Add support for [...]"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: "Is your feature request related to an existing problem? Please describe."
      placeholder: "It's hard to [...]"

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: "A clear and concise description of what you want to happen."
      placeholder: "Implement an adapter to [...]"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Additional Note
      description: "Add any other details or notes about the feature request here."
      placeholder: "Additional information"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests.
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md).
          required: true
