name: ❓ Question / Discussion
description: Ask a question or start a discussion about Charm
title: "[Question]: "
labels: [question]
body:
  - type: input
    id: topic
    attributes:
      label: Topic
      placeholder: "e.g. Edge Governance, adapter design"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question / Context
      description: "Please describe your question or what you’d like to understand better."
      placeholder: "How does Charm handle token quota management?"
    validations:
      required: true
